UnicoreApiUrl: https://zam2125.zam.kfa-juelich.de:9112/JUWELS/rest/core
Exclude:
  - '*.sif'
  - figures
  - saved_model
  - README.md
Resources:
  Nodes: 1
  Queue: develbooster
Environment:
  Variables:
    GIT_PYTHON_REFRESH: quiet
  PreRunCommandOnComputeNode: >
    module load Stages/2022 GCCcore/.11.2.0 NCCL/2.11.4-CUDA-11.5 Python/3.9.6;
    source /p/scratch/deepacf/maelstrom/grau1/ap1_env/bin/activate
