training:
    trainer:
        type: keras
    optimizer:
        type: adam
        learning_rate: 1.0e-2
    num_epochs: 20
    validation_frequency: 1 epoch # file
loader:
    type: file
    filenames: [ "data/air_temperature/5GB/2020*T*Z.nc"]
    normalization: "data/air_temperature/normalization.yml"
    cache_size: 2000
    predict_diff: True
    batch_size: 1
    prefetch: 1
    num_parallel_calls: 1
    debug: True
loader_validation:
    type: file
    filenames: ["data/air_temperature/5GB/202103*T*Z.nc"]
    normalization: "data/air_temperature/normalization.yml"
    cache_size: 200
    predict_diff: True
    batch_size: 1
    prefetch: 1
    num_parallel_calls: 1
    debug: False
loader_test:
    type: file
    filenames: ["data/air_temperature/5GB/2021*01T*Z.nc"]
    normalization: "data/air_temperature/normalization.yml"
    cache_size: 0
    predict_diff: True
    batch_size: 1
    prefetch: 1
    num_parallel_calls: 1
    debug: False
models:
    - type: BasicBenchmark
      name: cnn
      leadtime_dependent: False
      neighbourhood_size: 3
      filter_sizes: [12, 5, 5]
    - type: BasicBenchmark
      name: cnn_l5
      leadtime_dependent: False
      neighbourhood_size: 3
      filter_sizes: [12, 5, 5, 5, 5]
    - type: BasicBenchmark
      name: cnn_l5_r5
      leadtime_dependent: False
      neighbourhood_size: 5
      filter_sizes: [12, 5, 5, 5, 5]
    - type: BasicBenchmark
      name: cnn_lt
      leadtime_dependent: True
      neighbourhood_size: 3
      filter_sizes: [12, 5, 5]
    - type: BasicBenchmark
      name: cnn_norm
      leadtime_dependent: False
      neighbourhood_size: 3
      filter_sizes: [12, 5, 5]
      batch_normalization: True
    - type: BasicBenchmark
      name: cnn_separable
      leadtime_dependent: False
      neighbourhood_size: 3
      filter_sizes: [12, 5, 5]
      separable: True
    - type: Regression
      name: regression
    - type: Regression
      name: regression_lt
      leadtime_dependent: True
    - type: Unet
      name: unet
      levels: 3
      with_leadtime: False
    - type: Unet
      name: unet_lt
      with_leadtime: True
    - type: Custom
      name: custom
      final_activation: linear
      layers:
        - type: conv3d
          filters: 12
          kernel_size: [1, 3, 3]
          padding: same
          activation: "relu"
        - type: dense
          units: 12
          activation: "relu"
        - type: dense
          units: 12
          activation: "relu"
        - type: dense
          units: 12
          activation: "relu"
        - type: conv3d
          filters: 5
          kernel_size: [1, 3, 3]
          padding: same
          activation: "relu"
        - type: dense
          units: 5
          activation: "relu"
        - type: dense
          units: 5
          activation: "relu"
        - type: dense
          units: 5
          activation: "relu"
        - type: conv3d
          filters: 5
          kernel_size: [1, 3, 3]
          padding: same
          activation: "relu"
        - type: dense
          units: 5
          activation: "relu"
        - type: dense
          units: 5
          activation: "relu"
        - type: dense
          units: 5
          activation: "relu"
        - type: conv3d
          filters: 3
          kernel_size: [1, 3, 3]
          padding: same
          activation: "linear"
    - type: Custom
      name: cnn_custom_lt
      final_activation: linear
      layers:
        - type: conv3d
          filters: 12
          kernel_size: [1, 3, 3]
          padding: same
          activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 12
              activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 12
              activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 12
              activation: "relu"
        - type: conv3d
          filters: 5
          kernel_size: [1, 3, 3]
          padding: same
          activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 5
              activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 5
              activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 5
              activation: "relu"
        - type: conv3d
          filters: 5
          kernel_size: [1, 3, 3]
          padding: same
          activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 5
              activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 5
              activation: "relu"
        - type: leadtimelayer
          layer:
              type: dense
              units: 5
              activation: "relu"
        - type: conv3d
          filters: 3
          kernel_size: [1, 3, 3]
          padding: same
          activation: "linear"
    - type: Custom
      name: test
      layers:
          - type: dense
            units: 5
    - type: SelectPredictor
      name: raw
      predictor_names: ["air_temperature_2m", "air_temperature_0.1_2m", "air_temperature_0.9_2m"]
output:
    quantiles: [0.5, 0.1, 0.9]
loss:
    type: quantile_score
evaluators:
    - type: aggregator
tensorflow:
    num_threads: 2
